In [1]:
import numpy as np
import pandas as pd
import scipy
import seaborn as sns
import matplotlib.pyplot as plt

In [33]:
data = pd.read_csv('../data/unm.csv')
data = data[['datadate', 'cusip', 'niq','epspiq','cshprq']]
data.tail(60)

      datadate      cusip    niq  epspiq   cshprq
20  2009-03-31  91529Y106  164.9    0.50  330.805
21  2009-06-30  91529Y106  267.2    0.81  331.172
22  2009-09-30  91529Y106  221.1    0.67  331.411
23  2009-12-31  91529Y106  199.4    0.60  331.673
24  2010-03-31  91529Y106  229.8    0.69  332.270
25  2010-06-30  91529Y106  209.7    0.63  331.237
26  2010-09-30  91529Y106  220.8    0.68  323.083
27  2010-12-31  91529Y106  225.8    0.71  316.968
28  2011-03-31  91529Y106  223.6    0.72  312.742
29  2011-06-30  91529Y106  227.6    0.74  306.316
30  2011-09-30  91529Y106  202.0    0.68  298.186
31  2011-12-31  91529Y106 -369.0   -1.26  292.625
32  2012-03-31  91529Y106  213.9    0.74  290.430
33  2012-06-30  91529Y106  216.4    0.76  283.317
34  2012-09-30  91529Y106  230.2    0.83  278.354
35  2012-12-31  91529Y106  233.9    0.86  273.445
36  2013-03-31  91529Y106  212.6    0.79  269.361
37  2013-06-30  91529Y106  218.6    0.82  265.560
38  2013-09-30  91529Y106  205.7    0.78  262.946
39  2013-12-31  91529Y106  221.2    0.85  261.148
40  2014-03-31  91529Y106  225.8    0.87  259.409
41  2014-06-30  91529Y106  239.4    0.93  256.790
42  2014-09-30  91529Y106  219.1    0.86  253.586
43  2014-12-31  91529Y106 -282.2   -1.12  252.423
44  2015-03-31  91529Y106  212.9    0.85  251.467
45  2015-06-30  91529Y106  224.3    0.90  248.319
46  2015-09-30  91529Y106  203.8    0.83  245.400
47  2015-12-31  91529Y106  226.1    0.93  242.888
48  2016-03-31  91529Y106  210.6    0.88  239.619
49  2016-06-30  91529Y106  236.8    1.00  236.893
50  2016-09-30  91529Y106  236.0    1.01  233.752
51  2016-12-31  91529Y106  248.0    1.07  231.519
52  2017-03-31  91529Y106  229.9    1.00  229.430
53  2017-06-30  91529Y106  245.1    1.08  227.454
54  2017-09-30  91529Y106  252.3    1.12  225.288
55  2017-12-31  91529Y106  266.9    1.19  223.873
56  2018-03-31  91529Y106  273.5    1.23  221.894
57  2018-06-30  91529Y106  285.5    1.29  220.777
58  2018-09-30  91529Y106 -284.7   -1.30  218.893
59  2018-12-31  91529Y106  249.1    1.15  217.049
60  2019-03-31  91529Y106  280.9    1.31  214.297
61  2019-06-30  91529Y106  281.2    1.33  211.069
62  2019-09-30  91529Y106  242.0    1.16  208.098
63  2019-12-31  91529Y106  296.2    1.44  205.566
64  2020-03-31  91529Y106  161.0    0.79  203.306
65  2020-06-30  91529Y106  265.5    1.30  203.624
66  2020-09-30  91529Y106  231.1    1.13  203.761
67  2020-12-31  91529Y106  135.4    0.66  203.875
68  2021-03-31  91529Y106  153.0    0.75  204.133
69  2021-06-30  91529Y106  182.9    0.89  204.505
70  2021-09-30  91529Y106  328.6    1.61  204.646
71  2021-12-31  91529Y106  159.7    0.78  203.653
72  2022-03-31  91529Y106  240.4    1.19  202.629
73  2022-06-30  91529Y106  367.3    1.83  201.152
74  2022-09-30  91529Y106  510.3    2.55  200.035
75  2022-12-31  91529Y106  289.2    1.46  198.800
76  2023-03-31  91529Y106  358.3    1.81  198.111
77  2023-06-30  91529Y106  392.9    1.99  197.180
78  2023-09-30  91529Y106  202.0    1.03  196.083
79  2023-12-31  91529Y106  330.6    1.70  194.724

In [ ]:
### fps_eps_basic ff_net_income